const C=window.MOSAIC_MAGIC_CONFIG||{},API=String(C.SEARCH_API_URL||'').replace(/\/$/,'');
const queryEl=document.getElementById('query'),conn=document.getElementById('conn'),waiting=document.getElementById('waiting'),
panel=document.getElementById('panel'),grid=document.getElementById('grid'),timing=document.getElementById('timing'),
googleBtn=document.getElementById('googleBtn'),targetState=document.getElementById('targetState');
let lastCapture='',lastTarget='',current=null,start=0,busy=false,tbusy=false;
async function jf(url,opt){const r=await fetch(url,opt),d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||r.status);return d}
async function pollCapture(){if(busy)return;busy=true;try{const d=await jf(`${API}/latest?ts=${Date.now()}`,{cache:'no-store'});conn.textContent='已連線';const c=d.capture;if(c){const k=(c.query||'')+'|'+(c.capturedAt||'');if(k!==lastCapture){lastCapture=k;await load(c)}}}catch(e){conn.textContent='重試中…'}finally{busy=false}}
async function pollTarget(){if(tbusy)return;tbusy=true;try{const d=await jf(`${API}/target?ts=${Date.now()}`,{cache:'no-store'}),t=d.target;if(t){const k=(t.imageUrl||'')+'|'+(t.selectedAt||'');if(k!==lastTarget){lastTarget=k;targetState.textContent=t.source==='google-share'?'✓ Google Target Ready｜分享圖片已收到':'✓ Brave Target Ready';targetState.className='target-state ready'}}}catch(e){}finally{tbusy=false}}
async function load(c){current=c;start=performance.now();queryEl.textContent=c.query;waiting.classList.add('hidden');panel.classList.remove('hidden');grid.innerHTML='';targetState.textContent='尚未選定目標';targetState.className='target-state idle';
const d=await jf(`${API}/images?q=${encodeURIComponent(c.query)}`,{cache:'no-store'}),list=(d.results||[]).filter(x=>x.thumbnail||x.imageUrl).slice(0,4);
list.forEach((it,i)=>{const b=document.createElement('button');b.className='card';b.innerHTML=`<span class="num">${i+1}</span><img crossorigin="anonymous"><div class="meta"><div class="ready">載入中…</div><div class="src"></div></div>`;
const im=b.querySelector('img'),rd=b.querySelector('.ready');b.querySelector('.src').textContent=it.source||it.title||'';im.onload=()=>rd.textContent=`Ready ${((performance.now()-start)/1000).toFixed(2)}s`;im.src=it.thumbnail||it.imageUrl;b.onclick=()=>choose(it,i);grid.appendChild(b)});
timing.textContent=`候選取得 ${((performance.now()-start)/1000).toFixed(2)}s`}
async function choose(it,i){targetState.textContent=`送出 Brave 候選 ${i+1}…`;targetState.className='target-state loading';const t={query:current.query,imageUrl:it.imageUrl||it.thumbnail,thumbnail:it.thumbnail||it.imageUrl,title:it.title||'',source:'brave',selectedAt:new Date().toISOString(),candidate:i+1};await jf(`${API}/target`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(t)});targetState.textContent=`✓ Brave Target Ready｜候選 ${i+1}`;targetState.className='target-state ready'}
googleBtn.onclick=()=>{if(!current)return;targetState.textContent='Google 選圖中…';targetState.className='target-state loading';location.href=`https://www.google.com/search?tbm=isch&hl=zh-TW&q=${encodeURIComponent(current.query)}`};
pollCapture();pollTarget();setInterval(pollCapture,Number(C.MAGICIAN_POLL_MS||1000));setInterval(pollTarget,800);
